<a href="https://colab.research.google.com/github/ogut77/LogisticRegression/blob/master/LR%2BDA%2BRF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import data
import pandas as pd
data=pd.read_excel("https://hogut.weebly.com/uploads/1/8/1/6/18163409/bookbinder2.xls")
#Let's see first five observation
print(data[:5])



   Gender  Amount purchased  Frequency  Last purchase  First purchase  \
0       1               113          8              1               8   
1       1               418          6             11              66   
2       1               336         18              6              32   
3       1               180         16              5              42   
4       0               320          2              3              18   

   P_Child  P_Youth  P_Cook  P_DIY  P_Art     Staus Choice  
0        0        1       0      0      0  Training      Y  
1        0        2       3      2      3  Training      Y  
2        2        0       1      1      2  Training      Y  
3        2        0       0      1      1  Training      Y  
4        0        0       0      1      2  Training      Y  


In [2]:
#Descriptive Statistics
print(data.describe())

            Gender  Amount purchased    Frequency  Last purchase  \
count  3900.000000       3900.000000  3900.000000     3900.00000   
mean      0.675128        197.590256    12.897949        3.11641   
std       0.468387         95.784258     8.085644        2.94487   
min       0.000000         15.000000     2.000000        1.00000   
25%       0.000000        122.000000     8.000000        1.00000   
50%       1.000000        200.000000    12.000000        2.00000   
75%       1.000000        270.000000    16.000000        4.00000   
max       1.000000        474.000000    36.000000       12.00000   

       First purchase      P_Child      P_Youth       P_Cook        P_DIY  \
count     3900.000000  3900.000000  3900.000000  3900.000000  3900.000000   
mean        22.736410     0.733077     0.340513     0.775128     0.400000   
std         15.900152     1.031578     0.629651     1.050628     0.698439   
min          2.000000     0.000000     0.000000     0.000000     0.000000   
25

In [3]:
#Descriptive Statistcs of Categoric Variable Staus
data['Staus'].value_counts()


Test        2300
Training    1600
Name: Staus, dtype: int64

In [4]:
#Descriptive Statistcs of Categoric Variable Choice
#Choice is dependent variable
data['Choice'].value_counts()

N    3296
Y     604
Name: Choice, dtype: int64

In [5]:
#Descriptive Statistics of Numeric Variables
#when it is group by Choice ans Staus
data.groupby(['Choice','Staus']).mean()

Gender  Amount purchased  Frequency  Last purchase  \
Choice Staus                                                           
N      Test      0.70229        193.533397  13.720420       2.999046   
       Training  0.69750        194.416667  13.336667       2.951667   
Y      Test      0.52451        213.191176   9.029412       3.676471   
       Training  0.54250        220.412500   9.245000       3.940000   

                 First purchase   P_Child   P_Youth    P_Cook     P_DIY  \
Choice Staus                                                              
N      Test           22.969466  0.729485  0.341603  0.791985  0.413645   
       Training       22.546667  0.734167  0.327500  0.784167  0.393333   
Y      Test           21.598039  0.720588  0.352941  0.720588  0.328431   
       Training       22.665000  0.755000  0.367500  0.687500  0.385000   

                    P_Art  
Choice Staus               
N      Test      0.284351  
       Training  0.273333  
Y      Test      0.799020  
       Training  0.880000

In [10]:
import numpy as np
#Convert Categoric Data to 1 if Choice==Y and Choice==N 
data['Ch']=np.where(data['Choice'] =='Y', 1,0)
data.head(5)




Gender  Amount purchased  Frequency  Last purchase  First purchase  \
0       1               113          8              1               8   
1       1               418          6             11              66   
2       1               336         18              6              32   
3       1               180         16              5              42   
4       0               320          2              3              18   

   P_Child  P_Youth  P_Cook  P_DIY  P_Art     Staus Choice  Ch  
0        0        1       0      0      0  Training      Y   1  
1        0        2       3      2      3  Training      Y   1  
2        2        0       1      1      2  Training      Y   1  
3        2        0       0      1      1  Training      Y   1  
4        0        0       0      1      2  Training      Y   1

In [0]:
#Split Data into Trainig and Test if Staus Trainig and TEst respectively
Training = data['Staus']=='Training'
Test = data['Staus']=='Test'
TrainingData=data[Training]
TestData=data[Test]
#Select dependent variables and independent variables for Test and Train data
X_train=TrainingData.iloc[:,:-3]
X_test=TestData.iloc[:,:-3]
y_train=TrainingData.iloc[:,-1]
y_test=TestData.iloc[:,-1]


In [13]:
from sklearn.ensemble import RandomForestClassifier

RFC = RandomForestClassifier()  
             
RFC.fit(X_train, y_train)  
y_pred = RFC.predict(X_test)  
 

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(y_test,y_pred))
print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))

[[1919  177]
 [ 138   66]]
Accuracy score is 0.8630434782608696


In [17]:
#Logistic Regression Model
import statsmodels.api as sm

logit_model=sm.Logit(y_train,X_train)
result=logit_model.fit()
print(result.summary2())


Optimization terminated successfully.
         Current function value: 0.435889
         Iterations 6
                         Results: Logit
Model:              Logit            No. Iterations:   6.0000   
Dependent Variable: Ch               Pseudo R-squared: 0.225    
Date:               2019-03-10 01:59 AIC:              1414.8455
No. Observations:   1600             BIC:              1468.6230
Df Model:           9                Log-Likelihood:   -697.42  
Df Residuals:       1590             LL-Null:          -899.74  
Converged:          1.0000           Scale:            1.0000   
----------------------------------------------------------------
                  Coef.  Std.Err.    z    P>|z|   [0.025  0.975]
----------------------------------------------------------------
Gender           -0.9471   0.1271 -7.4510 0.0000 -1.1962 -0.6979
Amount purchased  0.0011   0.0006  1.7283 0.0839 -0.0001  0.0024
Frequency        -0.0898   0.0143 -6.2697 0.0000 -0.1178 -0.0617
Last purchase

In [19]:
#Confusion Matrix and Accuracy of Test Data

Y_TestScore = result.predict(X_test)
y_pred=np.where(Y_TestScore>0.5,1,0)
print(confusion_matrix(y_pred, y_test))
print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))


[[1961  125]
 [ 135   79]]
Accuracy score is 0.8869565217391304


In [20]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA(n_components=2)  
lda.fit_transform(X_train, y_train)  


array([[-0.39886209],
       [ 2.40033006],
       [ 0.7361476 ],
       ...,
       [ 1.08170446],
       [ 0.01509714],
       [-0.0259436 ]])

In [21]:
y_pred = lda.predict(X_test) 
print(confusion_matrix(y_test,y_pred))
print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))


[[1968  128]
 [ 127   77]]
Accuracy score is 0.8891304347826087
