<a href="https://colab.research.google.com/github/ogut77/LogisticRegression/blob/master/NaiveBayesUnderSamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [8]:
d2 = pd.read_csv('/content/drive/My Drive/Santander/train.csv')
d2.drop(['Unnamed: 0'], axis = 1, inplace = True)
d2.drop(['ID_code'], axis = 1, inplace = True)
d2.head(2)

target    var_0   var_1    var_2  var_3    var_4   var_5   var_6    var_7  \
0       0   8.9255 -6.7863  11.9081  5.093  11.4607 -9.2834  5.1187  18.6266   
1       0  11.5006 -4.1473  13.8588  5.389  12.3622  7.0433  5.6208  16.5338   

    var_8   ...     var_190  var_191  var_192  var_193  var_194  var_195  \
0 -4.9200   ...      4.4354   3.9642   3.1364   1.6910  18.5227  -2.3978   
1  3.1468   ...      7.6421   7.7214   2.5837  10.9516  15.4305   2.0339   

   var_196  var_197  var_198  var_199  
0   7.8784   8.5635  12.7803  -1.0914  
1   8.1267   8.7889  18.3560   1.9518  

[2 rows x 201 columns]

In [0]:
for col in d2.columns:
   d2.hist(column=col)
 

In [0]:
d2.describe()

target          var_0          var_1          var_2  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean        0.100490      10.679914      -1.627622      10.715192   
std         0.300653       3.040051       4.050044       2.640894   
min         0.000000       0.408400     -15.043400       2.117100   
25%         0.000000       8.453850      -4.740025       8.722475   
50%         0.000000      10.524750      -1.608050      10.580000   
75%         0.000000      12.758200       1.358625      12.516700   
max         1.000000      20.315000      10.376800      19.353000   

               var_3          var_4          var_5          var_6  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean        6.796529      11.078333      -5.065317       5.408949   
std         2.043319       1.623150       7.863267       0.866607   
min        -0.040200       5.074800     -32.562600       2.347300   
25%         5.254075       9.883175     -11.200350       4.767700   
50%         6.825000      11.108250      -4.833150       5.385100   
75%         8.324100      12.261125       0.924800       6.003000   
max        13.188300      16.671400      17.251600       8.447700   

               var_7          var_8      ...              var_190  \
count  200000.000000  200000.000000      ...        200000.000000   
mean       16.545850       0.284162      ...             3.234440   
std         3.418076       3.332634      ...             4.559922   
min         5.349700     -10.505500      ...           -14.093300   
25%        13.943800      -2.317800      ...            -0.058825   
50%        16.456800       0.393700      ...             3.203600   
75%        19.102900       2.937900      ...             6.406200   
max        27.691800      10.151300      ...            18.440900   

             var_191        var_192        var_193        var_194  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean        7.438408       1.927839       3.331774      17.993784   
std         3.023272       1.478423       3.992030       3.135162   
min        -2.691700      -3.814500     -11.783400       8.694400   
25%         5.157400       0.889775       0.584600      15.629800   
50%         7.347750       1.901300       3.396350      17.957950   
75%         9.512525       2.949500       6.205800      20.396525   
max        16.716500       8.402400      18.281800      27.928800   

             var_195        var_196        var_197        var_198  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean       -0.142088       2.303335       8.908158      15.870720   
std         1.429372       5.454369       0.921625       3.010945   
min        -5.261000     -14.209600       5.960600       6.299300   
25%        -1.170700      -1.946925       8.252800      13.829700   
50%        -0.172700       2.408900       8.888200      15.934050   
75%         0.829600       6.556725       9.593300      18.064725   
max         4.272900      18.321500      12.000400      26.079100   

             var_199  
count  200000.000000  
mean       -3.326537  
std        10.438015  
min       -38.852800  
25%       -11.208475  
50%        -2.819550  
75%         4.836800  
max        28.500700  

[8 rows x 201 columns]

In [3]:
from sklearn.model_selection import train_test_split

df, te = train_test_split(d2, test_size=0.2)
df.shape

(160000, 201)

In [0]:
no_frauds = len(df[df['target'] == 1])
non_fraud_indices = df[df.target == 0].index
import numpy as np
random_indices = np.random.choice(non_fraud_indices,no_frauds, replace=False)
fraud_indices = df[df.target == 1].index
under_sample_indices = np.concatenate([fraud_indices,random_indices])
under_sample = df.loc[under_sample_indices]
df=under_sample.copy()


In [0]:
df.describe()

target         var_0         var_1         var_2         var_3  \
count  32184.000000  32184.000000  32184.000000  32184.000000  32184.000000   
mean       0.500000     10.915777     -1.350917     10.903039      6.849213   
std        0.500008      3.150531      4.141988      2.744559      2.068340   
min        0.000000      0.930200    -14.037000      2.946200      0.373600   
25%        0.000000      8.592175     -4.503200      8.812600      5.296900   
50%        0.500000     10.745900     -1.316650     10.770500      6.879300   
75%        1.000000     13.039400      1.657800     12.733350      8.389300   
max        1.000000     19.559900      9.475400     19.353000     12.977300   

              var_4         var_5         var_6         var_7         var_8  \
count  32184.000000  32184.000000  32184.000000  32184.000000  32184.000000   
mean      11.107204     -4.788007      5.487249     16.530729      0.366424   
std        1.635172      7.991766      0.896818      3.417401      3.337077   
min        5.876200    -26.218000      2.758200      7.302400    -10.505500   
25%        9.899700    -11.021100      4.816375     13.928400     -2.234275   
50%       11.144950     -4.556700      5.473200     16.419150      0.481000   
75%       12.301300      1.181025      6.100400     19.060925      3.026150   
max       15.960400     16.907300      8.037900     27.060600      9.627200   

           ...            var_190       var_191       var_192       var_193  \
count      ...       32184.000000  32184.000000  32184.000000  32184.000000   
mean       ...           3.574997      7.625745      1.852783      3.235540   
std        ...           4.680444      3.106034      1.479643      4.033301   
min        ...         -11.878800     -2.343000     -3.317700    -11.783400   
25%        ...           0.159775      5.270375      0.805475      0.468250   
50%        ...           3.540300      7.545050      1.803500      3.314000   
75%        ...           6.841450      9.708800      2.872425      6.136150   
max        ...          17.043900     16.684600      7.679100     16.782600   

            var_194       var_195       var_196       var_197       var_198  \
count  32184.000000  32184.000000  32184.000000  32184.000000  32184.000000   
mean      17.901657     -0.091948      2.472573      8.866013     15.667178   
std        3.160259      1.448912      5.484542      0.937120      3.124586   
min        9.649200     -5.018500    -14.020400      6.119000      6.558700   
25%       15.536000     -1.145400     -1.753050      8.215500     13.575525   
50%       17.871700     -0.125500      2.637850      8.853800     15.734150   
75%       20.314400      0.892800      6.683950      9.560100     17.938600   
max       27.295300      4.088100     17.161400     11.706900     26.079100   

            var_199  
count  32184.000000  
mean      -2.988203  
std       10.380451  
min      -38.852800  
25%      -10.769350  
50%       -2.492250  
75%        5.143750  
max       24.564600  

[8 rows x 201 columns]

In [0]:
X_train=df.iloc[:,1:]
X_test=te.iloc[:,1:]
y_train=df.iloc[:,0:1]
y_test=te.iloc[:,0:1]

In [0]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train2 = sc.fit_transform(X_train) 
X_train=pd.DataFrame(X_train2, columns = X_train.columns)

X_test2 = sc.fit_transform(X_test) 
X_test=pd.DataFrame(X_test2, columns = X_train.columns)


In [0]:
def ldaf(X_train, y_train, X_test, y_test):
  print(X_test.shape)
  from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
  from sklearn.metrics import accuracy_score,confusion_matrix
  from sklearn.metrics import roc_curve, auc, roc_auc_score
  import matplotlib.pyplot as plt
  lda = LDA(n_components=2)  
  lda.fit_transform(X_train, y_train)

  y_pred = lda.predict(X_test) 
  predictions = lda.predict_proba(X_test)
  print(confusion_matrix(y_test,y_pred))
  print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))
  false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
  print("Area under ROC is "+str(auc(false_positive_rate, true_positive_rate)))
  return auc(false_positive_rate, true_positive_rate)

In [0]:
ldaf(X_train, y_train, X_test, y_test)

(40000, 200)


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[28255  7739]
 [  911  3095]]
Accuracy score is 0.78375
Area under ROC is 0.7787915282158165


0.7787915282158165

In [0]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import roc_curve, auc, roc_auc_score

RFC = RandomForestClassifier(n_estimators=50)  
             
RFC.fit(X_train, y_train)  
y_pred = RFC.predict(X_test)



print(confusion_matrix(y_test,y_pred))
print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
print(auc(false_positive_rate, true_positive_rate))
print(roc_auc_score(y_test, y_pred))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  import sys


[[26362  9673]
 [ 1119  2846]]
Accuracy score is 0.7302
0.7246735563067362
0.7246735563067362


In [0]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import roc_curve, auc, roc_auc_score
import matplotlib.pyplot as plt
model = XGBClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
predictions = model.predict_proba(X_test)

print(confusion_matrix(y_test,y_pred))
print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
print(auc(false_positive_rate, true_positive_rate))
print(roc_auc_score(y_test, y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[28332  7703]
 [ 1133  2832]]
Accuracy score is 0.7791
0.7502426445075555
0.7502426445075555


In [0]:
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import roc_curve, auc, roc_auc_score

LR=LogisticRegression()
LR.fit(X_train, y_train)
y_pred = LR.predict(X_test)
print(LogisticRegression(fit_intercept=True).get_params(deep=True))
print(confusion_matrix(y_test,y_pred))
print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
print(auc(false_positive_rate, true_positive_rate))
print(roc_auc_score(y_test, y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


{'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'max_iter': 100, 'multi_class': 'warn', 'n_jobs': None, 'penalty': 'l2', 'random_state': None, 'solver': 'warn', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}
[[20184 15707]
 [  409  3700]]
Accuracy score is 0.5971
0.7314158979190387
0.7314158979190387


In [0]:
def logistic_feature_importance(m,df):
    df=pd.DataFrame(df)
    return pd.DataFrame({'cols':df.columns, 'imp':abs(m.coef_[0])}).sort_values('imp', ascending=False)

In [0]:
lfi=logistic_feature_importance(LR,X_train);print(len(lfi.cols))

200


In [0]:
def nb(X_train, y_train, X_test, y_test):
 from sklearn.naive_bayes import GaussianNB
 from sklearn import metrics
 from sklearn.metrics import confusion_matrix,accuracy_score
 from sklearn.metrics import roc_curve, auc, roc_auc_score
 gnb = GaussianNB()
 gnb.fit(X_train, y_train)

 y_pred = gnb.predict(X_test)
 y_pred=pd.DataFrame(y_pred)
 print(confusion_matrix(y_test,y_pred))
 return (roc_auc_score(y_test, y_pred))

In [7]:
nb(X_train, y_train, X_test, y_test)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[29009  6948]
 [  810  3233]]


0.8032114595118083

In [0]:
for i in range(len(lfi.cols)-1,190,-1):
   to_keep = lfi.cols[0:i]
   print(len(to_keep))
   X_train3=X_train[to_keep].copy()
   X_train3=pd.DataFrame(X_train3)
   X_test3=X_test[to_keep].copy()
   X_test3=pd.DataFrame(X_test3)
   print(nb(X_train3, y_train, X_test3, y_test))
  

In [0]:
for i in range(len(lfi.cols)-1,100,-1):
   to_keep = lfi.cols[0:i]
   print(len(to_keep))
   X_train3=X_train[to_keep].copy()
   X_train3=pd.DataFrame(X_train3)
   X_test3=X_test[to_keep].copy()
   X_test3=pd.DataFrame(X_test3)
   print(ldaf(X_train3, y_train, X_test3, y_test))
  

In [0]:
X_train=X_train[to_keep].copy()
X_test=X_test[to_keep].copy()


In [0]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

gnb = GaussianNB()
gnb.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import roc_curve, auc, roc_auc_score

y_pred = gnb.predict(X_test)
y_pred=pd.DataFrame(y_pred)
y_pred.head()
print(confusion_matrix(y_test,y_pred))
print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
print(auc(false_positive_rate, true_positive_rate))
print(roc_auc_score(y_test, y_pred))

In [0]:
import numpy as np
import pandas as pd
import lightgbm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer

train_data = lightgbm.Dataset(X_train, label=y_train)
test_data = lightgbm.Dataset(X_test, label=y_test)
parameters = {
    'application': 'binary',
    'objective': 'binary',
    'metric': 'auc',
    'is_unbalance': 'true',
    'boosting': 'dart',
    'num_leaves': 31,
    'feature_fraction': 0.5,
    'bagging_fraction': 0.5,
    'bagging_freq': 20,
    'learning_rate': 0.05,
    'verbose': 0
}

modellbm = lightgbm.train(parameters,
                       train_data,
                       valid_sets=test_data,
                       num_boost_round=5000,
                       early_stopping_rounds=100)

In [0]:
submission = pd.read_csv('/content/drive/My Drive/Santander/test.csv')
submission.head(2)



Unnamed: 0 ID_code    var_0   var_1    var_2   var_3    var_4   var_5  \
0           0  test_0  11.0656  7.7798  12.9536  9.4292  11.4327 -2.3805   
1           1  test_1   8.5304  1.2543  11.3047  5.1858   9.1974 -4.0117   

    var_6    var_7   ...     var_190  var_191  var_192  var_193  var_194  \
0  5.8493  18.2675   ...     -2.1556  11.8495  -1.4300   2.4508  13.7112   
1  6.0196  18.6316   ...     10.6165   8.8349   0.9403  10.1282  15.5765   

   var_195  var_196  var_197  var_198  var_199  
0   2.4669   4.3654  10.7200  15.4722  -8.7197  
1   0.4773  -1.4852   9.8714  19.1293 -20.9760  

[2 rows x 202 columns]

In [0]:

y_pred = modellbm.predict(X_test)
y_pred=np.where(y_pred>0.5,1,0)
y_pred=pd.DataFrame(y_pred)
y_pred.describe()
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import roc_curve, auc, roc_auc_score


print(confusion_matrix(y_test,y_pred))
print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
print(auc(false_positive_rate, true_positive_rate))
print(roc_auc_score(y_test, y_pred))


[[28902  7133]
 [  767  3198]]
Accuracy score is 0.8025
0.8043054680445013
0.8043054680445013


In [0]:
y=pd.DataFrame(y)
y.head()

0
0  1
1  1
2  1
3  1
4  0

In [0]:
output = pd.DataFrame({'id': ids, 'target': y})
output.to_csv("/content/drive/My Drive/Santander/submission.csv", index=False)

In [0]:
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import roc_curve, auc, roc_auc_score


print(confusion_matrix(y_test,y_pred))
print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
print(auc(false_positive_rate, true_positive_rate))
print(roc_auc_score(y_test, y_pred))

[[28332  7703]
 [ 1133  2832]]
Accuracy score is 0.7791
0.7502426445075555
0.7502426445075555
