<a href="https://colab.research.google.com/github/ogut77/LogisticRegression/blob/master/Undersampling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
d2 = pd.read_csv('/content/drive/My Drive/Santander/train.csv')
d2.drop(['Unnamed: 0'], axis = 1, inplace = True)
d2.drop(['ID_code'], axis = 1, inplace = True)
d2.head(2)

target    var_0   var_1    var_2  var_3    var_4   var_5   var_6    var_7  \
0       0   8.9255 -6.7863  11.9081  5.093  11.4607 -9.2834  5.1187  18.6266   
1       0  11.5006 -4.1473  13.8588  5.389  12.3622  7.0433  5.6208  16.5338   

    var_8   ...     var_190  var_191  var_192  var_193  var_194  var_195  \
0 -4.9200   ...      4.4354   3.9642   3.1364   1.6910  18.5227  -2.3978   
1  3.1468   ...      7.6421   7.7214   2.5837  10.9516  15.4305   2.0339   

   var_196  var_197  var_198  var_199  
0   7.8784   8.5635  12.7803  -1.0914  
1   8.1267   8.7889  18.3560   1.9518  

[2 rows x 201 columns]

In [0]:
d2.describe()

target          var_0          var_1          var_2  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean        0.100490      10.679914      -1.627622      10.715192   
std         0.300653       3.040051       4.050044       2.640894   
min         0.000000       0.408400     -15.043400       2.117100   
25%         0.000000       8.453850      -4.740025       8.722475   
50%         0.000000      10.524750      -1.608050      10.580000   
75%         0.000000      12.758200       1.358625      12.516700   
max         1.000000      20.315000      10.376800      19.353000   

               var_3          var_4          var_5          var_6  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean        6.796529      11.078333      -5.065317       5.408949   
std         2.043319       1.623150       7.863267       0.866607   
min        -0.040200       5.074800     -32.562600       2.347300   
25%         5.254075       9.883175     -11.200350       4.767700   
50%         6.825000      11.108250      -4.833150       5.385100   
75%         8.324100      12.261125       0.924800       6.003000   
max        13.188300      16.671400      17.251600       8.447700   

               var_7          var_8      ...              var_190  \
count  200000.000000  200000.000000      ...        200000.000000   
mean       16.545850       0.284162      ...             3.234440   
std         3.418076       3.332634      ...             4.559922   
min         5.349700     -10.505500      ...           -14.093300   
25%        13.943800      -2.317800      ...            -0.058825   
50%        16.456800       0.393700      ...             3.203600   
75%        19.102900       2.937900      ...             6.406200   
max        27.691800      10.151300      ...            18.440900   

             var_191        var_192        var_193        var_194  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean        7.438408       1.927839       3.331774      17.993784   
std         3.023272       1.478423       3.992030       3.135162   
min        -2.691700      -3.814500     -11.783400       8.694400   
25%         5.157400       0.889775       0.584600      15.629800   
50%         7.347750       1.901300       3.396350      17.957950   
75%         9.512525       2.949500       6.205800      20.396525   
max        16.716500       8.402400      18.281800      27.928800   

             var_195        var_196        var_197        var_198  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean       -0.142088       2.303335       8.908158      15.870720   
std         1.429372       5.454369       0.921625       3.010945   
min        -5.261000     -14.209600       5.960600       6.299300   
25%        -1.170700      -1.946925       8.252800      13.829700   
50%        -0.172700       2.408900       8.888200      15.934050   
75%         0.829600       6.556725       9.593300      18.064725   
max         4.272900      18.321500      12.000400      26.079100   

             var_199  
count  200000.000000  
mean       -3.326537  
std        10.438015  
min       -38.852800  
25%       -11.208475  
50%        -2.819550  
75%         4.836800  
max        28.500700  

[8 rows x 201 columns]

In [0]:
from sklearn.model_selection import train_test_split

df, te = train_test_split(d2, test_size=0.2)
df.shape

(160000, 201)

In [0]:
no_frauds = len(df[df['target'] == 1])
non_fraud_indices = df[df.target == 0].index
import numpy as np
random_indices = np.random.choice(non_fraud_indices,no_frauds, replace=False)
fraud_indices = df[df.target == 1].index
under_sample_indices = np.concatenate([fraud_indices,random_indices])
under_sample = df.loc[under_sample_indices]
under_sample.shape


(32164, 201)

In [0]:
under_sample.describe()

target         var_0         var_1         var_2         var_3  \
count  32342.000000  32342.000000  32342.000000  32342.000000  32342.000000   
mean       0.500000     10.867230     -1.366689     10.911431      6.828313   
std        0.500008      3.154232      4.136864      2.732446      2.053904   
min        0.000000      0.452800    -14.037000      2.898200      0.178800   
25%        0.000000      8.526100     -4.516275      8.825475      5.276225   
50%        0.500000     10.702700     -1.329200     10.806800      6.874500   
75%        1.000000     13.001175      1.641700     12.748250      8.355800   
max        1.000000     19.737900     10.376800     18.635400     12.870600   

              var_4         var_5         var_6         var_7         var_8  \
count  32342.000000  32342.000000  32342.000000  32342.000000  32342.000000   
mean      11.085220     -4.754212      5.496070     16.543013      0.368749   
std        1.630003      7.971270      0.892515      3.424956      3.337766   
min        5.876200    -29.013300      2.496000      7.194300     -9.839100   
25%        9.890325    -10.976425      4.826200     13.926700     -2.237550   
50%       11.096450     -4.490700      5.487400     16.478750      0.470900   
75%       12.276475      1.217500      6.105275     19.090575      3.020500   
max       15.692500     16.806500      8.433000     26.865400      9.605300   

           ...            var_190       var_191       var_192       var_193  \
count      ...       32342.000000  32342.000000  32342.000000  32342.000000   
mean       ...           3.577111      7.626751      1.851008      3.244158   
std        ...           4.689915      3.120291      1.485528      4.006057   
min        ...         -11.878800     -2.343000     -3.317700    -11.783400   
25%        ...           0.185325      5.276725      0.796750      0.517825   
50%        ...           3.570650      7.546350      1.798300      3.308400   
75%        ...           6.838200      9.709900      2.876900      6.136250   
max        ...          17.569000     16.520500      7.647600     17.527300   

            var_194       var_195       var_196       var_197       var_198  \
count  32342.000000  32342.000000  32342.000000  32342.000000  32342.000000   
mean      17.930804     -0.088704      2.460554      8.867917     15.644937   
std        3.165620      1.452140      5.504417      0.936083      3.127068   
min        9.445400     -5.018500    -14.020400      6.277200      6.558700   
25%       15.567825     -1.133700     -1.802550      8.217850     13.575700   
50%       17.907650     -0.113900      2.548800      8.852100     15.700400   
75%       20.345925      0.898150      6.724000      9.564000     17.936650   
max       27.928800      4.272900     17.161400     11.866100     25.857100   

            var_199  
count  32342.000000  
mean      -3.000390  
std       10.500020  
min      -37.696200  
25%      -10.921175  
50%       -2.454000  
75%        5.268450  
max       27.534000  

[8 rows x 201 columns]

In [0]:
X_train=under_sample.iloc[:,1:]
X_test=te.iloc[:,1:]
y_train=under_sample.iloc[:,0:1]
y_test=te.iloc[:,0:1]

In [0]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()  
X_train = sc.fit_transform(X_train) 
X_test= sc.fit_transform(X_test) 

In [0]:
def ldaf(X_train, y_train, X_test, y_test):
  print(X_test.shape)
  from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
  from sklearn.metrics import accuracy_score,confusion_matrix
  from sklearn.metrics import roc_curve, auc, roc_auc_score
  import matplotlib.pyplot as plt
  lda = LDA(n_components=2)  
  lda.fit_transform(X_train, y_train)

  y_pred = lda.predict(X_test) 
  predictions = lda.predict_proba(X_test)
  print(confusion_matrix(y_test,y_pred))
  print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))
  false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
  print("Area under ROC is "+str(auc(false_positive_rate, true_positive_rate)))
  return auc(false_positive_rate, true_positive_rate)

In [0]:
ldaf(X_train, y_train, X_test, y_test)

(40000, 200)


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[28190  7794]
 [  914  3102]]
Accuracy score is 0.7823
Area under ROC is 0.7779070467795336


0.7779070467795336

In [0]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import roc_curve, auc, roc_auc_score

RFC = RandomForestClassifier()  
             
RFC.fit(X_train, y_train)  
y_pred = RFC.predict(X_test)



print(confusion_matrix(y_test,y_pred))
print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
print(auc(false_positive_rate, true_positive_rate))
print(roc_auc_score(y_test, y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  import sys


[[26788  9285]
 [ 1779  2148]]
Accuracy score is 0.7234
0.6447938509884793
0.6447938509884793


In [0]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.metrics import roc_curve, auc, roc_auc_score
import matplotlib.pyplot as plt
model = XGBClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
predictions = model.predict_proba(X_test)

print(confusion_matrix(y_test,y_pred))
print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
print(auc(false_positive_rate, true_positive_rate))
print(roc_auc_score(y_test, y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[28086  7903]
 [ 1110  2901]]
Accuracy score is 0.774675
0.7518330779746898
0.7518330779746898


In [0]:
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import roc_curve, auc, roc_auc_score

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print(confusion_matrix(y_test,y_pred))
print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
print(auc(false_positive_rate, true_positive_rate))
print(roc_auc_score(y_test, y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[28101  7972]
 [  863  3064]]
Accuracy score is 0.779125
0.7796215277213776
0.7796215277213776


In [0]:
[[28161  7779]
 [  942  3118]]
Accuracy score is 0.781975
0.7757681110553715
0.7757681110553715

In [0]:
def logistic_feature_importance(m,df):
    return pd.DataFrame({'cols':df.columns, 'imp':abs(m.coef_[0])}
                       ).sort_values('imp', ascending=False)

In [0]:
lfi=logistic_feature_importance(model,X_train); lfi.cols[5:]

NameError: ignored

In [0]:
to_keep = lfi[lfi.imp>0.025].cols; len(to_keep)

88

In [0]:
X_train=X_train[to_keep].copy()
X_test=X_test[to_keep].copy()


In [0]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics

gnb = GaussianNB()
gnb.fit(X_train, y_train)
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import roc_curve, auc, roc_auc_score

y_pred = gnb.predict(X_test)
y_pred=pd.DataFrame(y_pred)
y_pred.head()
print(confusion_matrix(y_test,y_pred))
print("Accuracy score is "+str(accuracy_score(y_test,y_pred)))
false_positive_rate, true_positive_rate, thresholds = roc_curve(y_test, y_pred)
print(auc(false_positive_rate, true_positive_rate))
print(roc_auc_score(y_test, y_pred))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[29215  6858]
 [  748  3179]]
Accuracy score is 0.80985
0.8097046597309951
0.8097046597309951


In [0]:
import numpy as np
import pandas as pd
import lightgbm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer


In [0]:
train_data = lightgbm.Dataset(X_train, label=y_train)
test_data = lightgbm.Dataset(X_test, label=y_test)

In [0]:
parameters = {
    'application': 'binary',
    'objective': 'binary',
    'metric': 'auc',
    'is_unbalance': 'true',
    'boosting': 'gbdt',
    'num_leaves': 31,
    'feature_fraction': 0.5,
    'bagging_fraction': 0.5,
    'bagging_freq': 20,
    'learning_rate': 0.05,
    'verbose': 0
}

modellbm = lightgbm.train(parameters,
                       train_data,
                       valid_sets=test_data,
                       num_boost_round=5000,
                       early_stopping_rounds=100)

[1]	valid_0's auc: 0.631659
Training until validation scores don't improve for 100 rounds.
[2]	valid_0's auc: 0.679301
[3]	valid_0's auc: 0.697411
[4]	valid_0's auc: 0.710527
[5]	valid_0's auc: 0.716583
[6]	valid_0's auc: 0.723031
[7]	valid_0's auc: 0.729562
[8]	valid_0's auc: 0.739242
[9]	valid_0's auc: 0.747383
[10]	valid_0's auc: 0.751265
[11]	valid_0's auc: 0.756073
[12]	valid_0's auc: 0.761003
[13]	valid_0's auc: 0.765167
[14]	valid_0's auc: 0.769544
[15]	valid_0's auc: 0.77308
[16]	valid_0's auc: 0.774503
[17]	valid_0's auc: 0.777576
[18]	valid_0's auc: 0.779099
[19]	valid_0's auc: 0.779359
[20]	valid_0's auc: 0.781433
[21]	valid_0's auc: 0.78284
[22]	valid_0's auc: 0.785964
[23]	valid_0's auc: 0.786825
[24]	valid_0's auc: 0.787657
[25]	valid_0's auc: 0.791029
[26]	valid_0's auc: 0.792392
[27]	valid_0's auc: 0.794464
[28]	valid_0's auc: 0.796274
[29]	valid_0's auc: 0.79793
[30]	valid_0's auc: 0.799763
[31]	valid_0's auc: 0.80101
[32]	valid_0's auc: 0.802827
[33]	valid_0's auc: 0.

In [0]:
submission = pd.read_csv('/content/drive/My Drive/Santander/test.csv')
submission.head(2)



Unnamed: 0 ID_code    var_0   var_1    var_2   var_3    var_4   var_5  \
0           0  test_0  11.0656  7.7798  12.9536  9.4292  11.4327 -2.3805   
1           1  test_1   8.5304  1.2543  11.3047  5.1858   9.1974 -4.0117   

    var_6    var_7   ...     var_190  var_191  var_192  var_193  var_194  \
0  5.8493  18.2675   ...     -2.1556  11.8495  -1.4300   2.4508  13.7112   
1  6.0196  18.6316   ...     10.6165   8.8349   0.9403  10.1282  15.5765   

   var_195  var_196  var_197  var_198  var_199  
0   2.4669   4.3654  10.7200  15.4722  -8.7197  
1   0.4773  -1.4852   9.8714  19.1293 -20.9760  

[2 rows x 202 columns]

In [0]:
submission.drop(['Unnamed: 0'], axis = 1, inplace = True)
ids = submission['ID_code'].values
submission.drop(['ID_code'], axis = 1, inplace = True)
x = submission.values
y = model.predict(x)
y= np.where(y < 0.5, 0, 1)



In [0]:
y=pd.DataFrame(y)
y.head()

0
0  1
1  1
2  1
3  1
4  0

In [0]:
y.describe()

0
count  200000.000000
mean        0.254070
std         0.435338
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000

In [0]:
output = pd.DataFrame({'id': ids, 'target': y})
output.to_csv("/content/drive/My Drive/Santander/submission.csv", index=False)